# Generated by Django 4.0.10 on 2024-02-24 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('SAPCode', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=100)),
                ('YearOfEstablishment', models.DateField()),
                ('TypeOfFirm', models.CharField(max_length=100)),
                ('TypeOfSite', models.CharField(max_length=100)),
                ('vruoomAdminId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
