# Generated by Django 4.0.10 on 2024-03-24 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dionysus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='AutomationType',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='AverageSaleVolumeHSD',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='AverageSaleVolumeMS',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='HoursOfOperation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('mobileNo', models.CharField(max_length=100)),
                ('whatsappNo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('dateOfJoining', models.DateField()),
                ('dateOfLeaving', models.DateField()),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dionysus.client')),
            ],
        ),
    ]
